version: "3.7"
services:
  redis:
    image: redis
    volumes:
      - ./redis:/data
    ports:
      - "6380:6379"
  node:
    build:
      dockerfile: Dockerfile
      context: ./node
    volumes:
      - /app/node_modules
      - ./node:/app
    ports:
      - "3310:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
